// AUTOGENERATED by tools/gen_board_data.py — do not edit.
#pragma once
#include <array>
#include <cstdint>
#include "types.hpp"

namespace seq {

constexpr int N_CARD_TYPES = 50;
constexpr int N_REGULAR_CARDS = 48;
constexpr int ONE_EYED_JACK = 48;
constexpr int TWO_EYED_JACK = 49;
constexpr int N_WINDOWS = 192;

// cell index (0..99) -> card type (0..47), or -1 for joker corner
extern const int8_t CELL_TO_CARD[100];

// regular card type (0..47) -> two cell indices on the board (-1 if absent)
extern const int8_t CARD_TO_CELLS[N_REGULAR_CARDS][2];

// joker corners
extern const BB100 JOKER_MASK;

// 5-in-a-row windows
extern const BB100 WINDOW_MASKS[N_WINDOWS];

// per-cell list of windows passing through it (variable length, terminated by -1).
// int16_t because window indices run 0..191 — doesn't fit in int8_t.
constexpr int MAX_WINDOWS_PER_CELL = 20;
extern const int16_t CELL_WINDOWS[100][MAX_WINDOWS_PER_CELL + 1];

const char* card_name(int card_idx);

} // namespace seq
